# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-09 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
